<h1 align="center">INFO621 - Advanced Machine Learning Applications</h1>

<h2 align="center"><strong>Homework 3: Transformers and CNNs</strong></h2>

# Guidelines

**Worth:** 10% of your final grade (**100 points total**)  
**Submission Deadline:** Friday, March 07, 11:59 PM (Tucson Time)


### **Instructions**

- For exercises involving code, write your solutions in the provided code chunks. You may add additional code chunks if needed.  
- For exercises requiring descriptions or interpretations, use full sentences and provide clear, concise explanations.  

### **Policies**

**Sharing/Reusing Code Policy:**  
You are allowed to use online resources (e.g., RStudio Community, StackOverflow) but **must explicitly cite** any external code you use or adapt. Failure to do so will be considered plagiarism, regardless of the source.  

**Late Submission Policy:**  
- **Less than 1 day late:** -25% of available points.  
- **1-7 days late:** -50% of available points.  
- **7 days or more late:** No credit will be awarded, and feedback will not be provided.  

**Declaration of Independent Work:**  
You must acknowledge your submission as your independent work by including your **name** and **date** at the end of the "Declaration of Independent Work" section.  

### **Grading**

- **Total Points:** 100 points.

- **Grade Breakdown:**  
  - **Part 1 (40 Points Total):**  
    - Multiple-Choice Questions: 5 questions, 4 points each.  
    - Descriptive Questions: 4 questions, 5 points each.  

  - **Part 2 (45 Points Total):**  
    - 9 code completion tasks.  

  - **Part 3 (15 Points Total):**  
    - 2 code completion task.  

# Part 1. Written Questions (40 points)

- **Multiple-Choice Questions**: 5 questions, 4 points each  
- **Descriptive Questions**: 4 questions, 5 points each

## 1.1 Multiple-Choice Questions (20 points)

1. **Which mechanism enables Transformers to capture global dependencies among tokens? (4 points)**

  - A) Convolution
  - B) Self-Attention
  - C) Recurrent Processing
  - D) Max-Pooling
  - E) Fully Connected Layers

**Your Answer**: B

2. **What is the primary purpose of positional embeddings in Transformers? (4 points)**

  - A) To reduce the dimensionality of token embeddings
  - B) To normalize the activations
  - C) To initialize the weight matrices
  - D) To encode the order of the tokens
  - E) To improve token similarity calculations

**Your Answer**: E

3. **In Convolutional Neural Networks (CNNs), what advantage does the convolution operation provide? (4 points)**

  - A) Global connectivity with all image pixels
  - B) Sequential processing of image rows
  - C) Automatic extraction of textual features
  - D) Increased interpretability of model decisions
  - E) Local connectivity with parameter sharing


**Your Answer**: E

4. **Which component in a Transformer block is responsible for introducing non-linearity after the self-attention mechanism? (4 points)**

  - A) Self-Attention
  - B) Feed-Forward Network (FNN)
  - C) Positional Encoding
  - D) Residual Connection
  - E) Layer Normalization

**Your Answer**: B

5. **What is the role of residual connections in deep Transformer architectures? (4 points)**

  - A) They help alleviate vanishing gradients and ease training
  - B) They add extra parameters to the model
  - C) They perform dimensionality reduction
  - D) They serve as pooling operations
  - E) They replace the need for self-attention layers

**Your Answer**: A

## 1.2 Open-Ended Questions (20 points)

## **Q1. Understanding Self-Attention in Transformers (5 points)**

### **Scenario**  
Imagine you are designing a **language model** for **text generation**, such as an **autocorrect system**. Your model needs to understand the relationships between words in a sentence, regardless of their positions. Traditional models like RNNs struggle with **long-range dependencies**, meaning that words appearing far apart in a sentence may not influence each other effectively.  

### **Question**  
How does the **self-attention mechanism** help capture long-range dependencies in a sequence, and why is it more effective than recurrent layers in this regard?  

### **Hint**  
Think about how **queries, keys, and values** are used in self-attention and how the **dot-product attention mechanism** allows the model to focus on **all tokens simultaneously** rather than sequentially.  


### **Your Answer:**  Self-attention helps to capture long range dependencies in a sequence because it uses the dot-product attentuon mechanism, which allows the model to look at all tokens in the data rather than one by one, so the weights from all tokens can influence the model for the word the model is trying to predict. Its more efficient since reccurent layers operate sequentially, so tokens that are farther from the word of interest have less influence while tokens closer are more influential.

## **Q2. The Role of Positional Embeddings in Transformers (5 points)**

### **Scenario**  
In models like **RNNs**, token order is naturally encoded by processing words sequentially. However, in **Transformers**, words are processed **in parallel**, which means the model lacks any **built-in notion of word order**. Without a mechanism to encode order, a Transformer would treat a sentence like "The cat chased the dog" the same as "The dog chased the cat."  

### **Question**  
Why do Transformers require **positional embeddings**, and how do **sinusoidal positional encodings** help the model differentiate between token positions?  

### **Hint**  
Consider how positional embeddings are **added to word embeddings** and how sinusoidal functions provide a **continuous, fixed representation** of position information.  


### **Your Answer:**   The positional embeddings retain information about where input data (words) are located in the sequence (sentence), which is important so the transformer has the spatial relationships of the words as well as the contextual ones. The sinusoidal positional encodings help to differentiate between token positions because they provide a smooth continuous method of locating position that is bound between -1 and 1, which is easier for the model to understand and provides global and local location relationships.

## **Q3. Feature Extraction in Convolutional Neural Networks (CNNs) (5 points)**  

### **Scenario**  
You are developing a **facial recognition system** using images captured from security cameras. To correctly classify faces, your system must learn to recognize **features such as edges, textures, and patterns**, rather than memorizing specific pixel values. Fully connected layers struggle with this because they lack spatial awareness.  

### **Question**  
How does the **convolution operation** in CNNs enable the model to learn and extract important features from images? What advantages does convolution provide over fully connected layers for image-based tasks?  

### **Hint**  
Think about how **local receptive fields** and **parameter sharing** allow CNNs to capture **spatial hierarchies** while reducing the number of parameters compared to fully connected layers.


### **Your Answer:**  The convolution operation is an effective way of extracting important features since it uses a filter to connect pixels in close proximity of each other which helps to extract useful features that are larger than the pixel scale . Convolution is advantagous because it reduces the amount of parameters that the model has to interpret when compared to fully connected layers.

## **Q4. The Effect of Max-Pooling in CNNs (5 points)**  

### **Scenario**  
Suppose you are working on an **image classification task** where your model needs to recognize objects in pictures taken from **different angles and distances**. You notice that small shifts in an object’s position within the image can cause **inconsistent feature activations**, making the model **sensitive to slight changes**.  

### **Question**  
How does **max-pooling** help improve the **spatial invariance** of a CNN, and what effect does it have on the **size and complexity** of feature maps?  

### **Hint**  
Consider how **max-pooling reduces dimensionality**, improves **robustness to small translations**, and prevents the model from being **overly sensitive to exact pixel positions**.  


### **Your Answer:**   Max-pooling improves the spatial invariance of a CNN since it decreases the size and complexity of the feature map by taking the maximum pixel value in an area as the representative value of that area. This decreases the amount of variance in a small area and ensures the model focuses on the most important parameters in since it generalizes a value (the max value) for all of the positions in the area of focus.

# **Section 2: Implementing Transformers (45 Points)**


## **Objective**
In this section, you will implement a simplified Transformer block from scratch. Your implementation should focus on four core components:

1. **Self-Attention:** Compute queries, keys, and values from the input, then apply the scaled dot-product attention mechanism.
2. **Feed-Forward Neural Network (FNN):** Build a two-layer fully connected network with a ReLU activation to introduce non-linearity.
3. **Positional Embeddings:** Compute sinusoidal positional encodings and add them to the input embeddings to provide sequence order information.
4. **Transformer Block Assembly:** Integrate the components using residual connections to form a complete Transformer block.


In [91]:
import numpy as np

## Task 2.1: Self-Attention (Missing Blocks: 2 / Total Points: 10)

### Description
Implement the self-attention mechanism. Use the provided fixed weight matrices (do not modify these initializations) to compute the query (Q), key (K), and value (V) vectors from the input tensor. Then compute the scaled dot-product attention by:
- Calculating the dot product between Q and the transpose of K, scaled by the square root of the model dimension.
- Applying a softmax (with numerical stability adjustments) to obtain the attention weights.
- Multiplying these weights with V to produce the self-attention output.


In [92]:
def self_attention(x):
    """
    Compute self-attention on the input tensor.

    Args:
      x: Input tensor of shape (batch_size, seq_length, embedding_dim)

    Returns:
      attn_output: Tensor after applying self-attention.
    """
    d_model = x.shape[-1]

    W_Q = np.full((d_model, d_model), 1.0)   # All ones
    W_K = np.full((d_model, d_model), 2.0)     # All twos
    W_V = np.full((d_model, d_model), 3.0)     # All threes

    # #############################################################
    # Your Turn: Compute queries, keys, and values from input x.
    # -------------------------------------------------------------
    q = x @ W_Q
    k = x @ W_K
    v = x @ W_V
    # #############################################################


    # #############################################################
    # Your Turn: Compute the scaled dot-product attention.
    #   - Compute scores = Q * K^T / sqrt(d_model)
    #   - Apply softmax to scores (subtracting max for numerical stability)
    #   - Compute attn_output = weights * V
    # -------------------------------------------------------------
    scores = q @ k.transpose(0,2,1)/np.sqrt(d_model)
    weights = (np.exp(scores - np.max(scores)))/(np.sum(np.exp(scores))) 
    attn_output = weights @ v
    # #############################################################

    return attn_output
  

dummy_input_sa = np.ones((2, 5, 8))
sa_output = self_attention(dummy_input_sa)
print("Task 2.1 - Self-Attention Output:")
print(sa_output)
sa_output.shape

Task 2.1 - Self-Attention Output:
[[[1.40868461e-157 1.40868461e-157 1.40868461e-157 1.40868461e-157
   1.40868461e-157 1.40868461e-157 1.40868461e-157 1.40868461e-157]
  [1.40868461e-157 1.40868461e-157 1.40868461e-157 1.40868461e-157
   1.40868461e-157 1.40868461e-157 1.40868461e-157 1.40868461e-157]
  [1.40868461e-157 1.40868461e-157 1.40868461e-157 1.40868461e-157
   1.40868461e-157 1.40868461e-157 1.40868461e-157 1.40868461e-157]
  [1.40868461e-157 1.40868461e-157 1.40868461e-157 1.40868461e-157
   1.40868461e-157 1.40868461e-157 1.40868461e-157 1.40868461e-157]
  [1.40868461e-157 1.40868461e-157 1.40868461e-157 1.40868461e-157
   1.40868461e-157 1.40868461e-157 1.40868461e-157 1.40868461e-157]]

 [[1.40868461e-157 1.40868461e-157 1.40868461e-157 1.40868461e-157
   1.40868461e-157 1.40868461e-157 1.40868461e-157 1.40868461e-157]
  [1.40868461e-157 1.40868461e-157 1.40868461e-157 1.40868461e-157
   1.40868461e-157 1.40868461e-157 1.40868461e-157 1.40868461e-157]
  [1.40868461e-157 

(2, 5, 8)

## Task 2.2: Feed-Forward Network (Missing Blocks: 3 / Total Points: 15)

### Description
Implement a two-layer feed-forward network that processes the output from the self-attention sub-layer. Use the fixed weight and bias initializations provided:
- **First layer:** Expands the dimension by a factor of 4 (weights set to all ones, biases set to zeros).
- **Second layer:** Projects back to the original dimension (weights set to all ones, biases set to zeros).

Apply a ReLU activation after the first layer.

In [93]:
def feed_forward(x):
    """
    Compute the output of a two-layer feed-forward network.

    Args:
      x: Input tensor of shape (batch_size, seq_length, embedding_dim)

    Returns:
      output: Tensor after applying the feed-forward network.
    """
    d_model = x.shape[-1]
    d_ff = d_model * 4  # Expansion factor

    #############################################################
    # Your Turn: Define weights and biases for the first linear layer.
    # -----------------------------------------------------------
    w1 = np.ones((d_model, d_ff))
    biases1 = np.zeros((d_ff))
    
    #############################################################

    # #############################################################
    # Your Turn: Define weights and biases for the second linear layer.
    # -------------------------------------------------------------
    w2 = np.ones((d_ff, d_model))
    biases2 = np.zeros((d_model))
    # #############################################################

    # #############################################################
    # Your Turn: Compute the feed-forward output.
    #   - Compute hidden = x * W1 + b1, then apply ReLU.
    #   - Compute output = hidden * W2 + b2.
    # -------------------------------------------------------------
    hidden = x @ w1 + biases1
    relu_hidden = np.maximum(0,hidden)
    output = relu_hidden @ w2 + biases2
    # #############################################################

    return output

dummy_input_ffn = np.full((2, 5, 8), 24.0)
ffn_output = feed_forward(dummy_input_ffn)
print("\nTask 2.2 - Feed-Forward Network Output:")
print(ffn_output)
ffn_output.shape


Task 2.2 - Feed-Forward Network Output:
[[[6144. 6144. 6144. 6144. 6144. 6144. 6144. 6144.]
  [6144. 6144. 6144. 6144. 6144. 6144. 6144. 6144.]
  [6144. 6144. 6144. 6144. 6144. 6144. 6144. 6144.]
  [6144. 6144. 6144. 6144. 6144. 6144. 6144. 6144.]
  [6144. 6144. 6144. 6144. 6144. 6144. 6144. 6144.]]

 [[6144. 6144. 6144. 6144. 6144. 6144. 6144. 6144.]
  [6144. 6144. 6144. 6144. 6144. 6144. 6144. 6144.]
  [6144. 6144. 6144. 6144. 6144. 6144. 6144. 6144.]
  [6144. 6144. 6144. 6144. 6144. 6144. 6144. 6144.]
  [6144. 6144. 6144. 6144. 6144. 6144. 6144. 6144.]]]


(2, 5, 8)

## Task 2.3: Positional Embeddings (Missing Block: 1 / Total Points: 10)

### Description
Compute sinusoidal positional encodings and add them to the input tensor. For each position `pos` and each dimension `i`, you will:
- Compute `angle = pos / (10000^(2*(i//2)/d_model))`.
- Use `sin(angle)` for even indices and `cos(angle)` for odd indices.
Finally, add the computed positional encodings to the input tensor.

In [94]:
def positional_encoding(x):
    """
    Add sinusoidal positional encodings to the input tensor.

    Args:
      x: Input tensor of shape (batch_size, seq_length, embedding_dim)

    Returns:
      Tensor with positional encodings added.
    """
    batch_size, seq_length, d_model = x.shape
    pos_enc = np.zeros((seq_length, d_model))

    # #############################################################
    # Your Turn: Compute sinusoidal positional encodings.
    #   For each position pos and each dimension i:
    #     angle = pos / (10000^(2*(i//2)/d_model))
    #     Use sin(angle) if i is even, cos(angle) if i is odd.
    # -------------------------------------------------------------
    #
    for pos in range(seq_length):
        for i in range(d_model):
            angle = pos / (10000 ** (2 * (i // 2) / d_model))
            if i % 2 == 0:
                pos_enc[pos, i] = np.sin(angle)
            else:
                pos_enc[pos, i] = np.cos(angle)
    # #############################################################
    return x + pos_enc

dummy_input_pe = np.ones((2, 5, 8))
pe_output = positional_encoding(dummy_input_pe)
print("\nTask 2.3 - Positional Encoding Output (first example):")
print(pe_output[0])
pe_output[0].shape


Task 2.3 - Positional Encoding Output (first example):
[[1.         2.         1.         2.         1.         2.
  1.         2.        ]
 [1.84147098 1.54030231 1.09983342 1.99500417 1.00999983 1.99995
  1.001      1.9999995 ]
 [1.90929743 0.58385316 1.19866933 1.98006658 1.01999867 1.99980001
  1.002      1.999998  ]
 [1.14112001 0.0100075  1.29552021 1.95533649 1.0299955  1.99955003
  1.003      1.9999955 ]
 [0.2431975  0.34635638 1.38941834 1.92106099 1.03998933 1.99920011
  1.00399999 1.999992  ]]


(5, 8)

## Task 2.4: Transformer Block Assembly (Missing Blocks: 3 / Total Points: 10)

### Description
Assemble the full Transformer block by integrating the positional encoding, self-attention, and feed-forward network using residual connections. Your tasks are:
- Apply the positional encoding to the input tensor.
- Compute the self-attention output and add it to the input (residual connection).
- Compute the feed-forward network output and add it to the result (residual connection).

In [95]:
def transformer_block(x):
    """
    Assemble the Transformer block.

    Args:
      x: Input tensor of shape (batch_size, seq_length, embedding_dim)

    Returns:
      Output tensor after processing through the Transformer block.
    """
    # #############################################################
    # Your Turn: Apply positional encoding.
    # -------------------------------------------------------------
    encode = positional_encoding(x)
    # #############################################################

    # #############################################################
    # Your Turn: Compute self-attention output and add a residual connection.
    # -------------------------------------------------------------
    self_atten = self_attention(encode) + encode
    # #############################################################

    # #############################################################
    # Your Turn: Compute feed-forward network output and add a residual connection.
    # -------------------------------------------------------------
    x = feed_forward(self_atten) + self_atten
    # #############################################################

    return x

dummy_input_tb = np.ones((2, 5, 8))  # Fixed dummy input: tensor of ones
tb_output = transformer_block(dummy_input_tb)
print("\nTask 2.4 - Transformer Block Output:")
print(tb_output)


Task 2.4 - Transformer Block Output:
[[[385.         386.         385.         386.         385.
   386.         385.         386.        ]
  [401.44339758 401.1422289  400.70176001 401.59693076 400.61192643
   401.6018766  400.6029266  401.6019261 ]
  [376.1071589  374.78171463 375.3965308  376.17792805 375.21786014
   376.19766148 375.19986147 376.19785947]
  [335.04592758 333.91481508 335.20032778 335.86014406 334.93480307
   335.90435761 334.90780757 335.90480307]
  [318.42606632 318.52922519 319.57228715 320.1039298  319.22285814
   320.18206892 319.1868688  320.18286081]]

 [[385.         386.         385.         386.         385.
   386.         385.         386.        ]
  [401.44339758 401.1422289  400.70176001 401.59693076 400.61192643
   401.6018766  400.6029266  401.6019261 ]
  [376.1071589  374.78171463 375.3965308  376.17792805 375.21786014
   376.19766148 375.19986147 376.19785947]
  [335.04592758 333.91481508 335.20032778 335.86014406 334.93480307
   335.90435761 334.

/var/folders/6n/cwl6lb1j5j54r8zxq47cqpbr0000gn/T/ipykernel_32585/1288163090.py:33: RuntimeWarning: overflow encountered in exp
  weights = (np.exp(scores - np.max(scores)))/(np.sum(np.exp(scores)))


# Section 3: Implementing CNNs (15 Points)

## Objective
In this section you will implement a simplified Convolutional Neural Network (CNN). Your implementation focuses on two core components:
1. **Convolution:** Apply a convolution operation on a 2D input (image) using a fixed kernel. The convolution is performed by sliding the kernel over the image, computing element-wise products, and summing them to produce a feature map.
2. **Max-Pooling:** Apply a max-pooling operation on the feature map to downsample it by selecting the maximum value from non-overlapping pooling regions.

## Task 3.1: Convolution (Missing Blocks: 1 / Total Points: 10)

### Description
Implement the convolution operation for a 2D input image using a fixed kernel. The convolution is performed by sliding the kernel over the image, computing the element-wise product between the kernel and the current patch, and summing the results to form the output pixel value.

In [96]:
def conv_layer(x, kernel):
    """
    Apply convolution on the input image using the given kernel.

    Args:
      x: 2D input array (e.g., an image) of shape (H, W)
      kernel: Convolution kernel (filter) of shape (kH, kW)

    Returns:
      Output array of shape (H - kH + 1, W - kW + 1)
    """
    H, W = x.shape
    kH, kW = kernel.shape
    output_H = H - kH + 1
    output_W = W - kW + 1
    output = np.zeros((output_H, output_W))

    # #############################################################
    # Your Turn: Slide the kernel over the image and compute the dot product for each patch.
    # -------------------------------------------------------------
    for i in range(output_H):
        for j in range(output_W):
            patch = x[i:i+kH, j:j+kW]
            output[i, j] = np.sum(patch * kernel)  # Output array of shape (H - kH + 1, W - kW + 1)
    # #############################################################

    return output

dummy_image = np.array([[1, 2, 3, 4],
                        [5, 6, 7, 8],
                        [9,10,11,12],
                        [13,14,15,16]])
kernel = np.array([[1, 0],
                   [0, -1]])
conv_output = conv_layer(dummy_image, kernel)
print("Task 3.1 - Convolution Output:")
print(conv_output)

Task 3.1 - Convolution Output:
[[-5. -5. -5.]
 [-5. -5. -5.]
 [-5. -5. -5.]]


## Task 3.2: Max-Pooling (Missing Block: 1 / Total Points: 5)

### Description
Implement the max-pooling operation on a 2D feature map. The max-pooling operation divides the input into non-overlapping regions of a specified window size and selects the maximum value from each region, producing a downsampled output.

In [97]:
def max_pooling(x, pool_size):
    """
    Apply max-pooling to the input feature map.

    Args:
      x: 2D input array (e.g., a feature map)
      pool_size: Size of the pooling window (assume square)

    Returns:
      Pooled output array.
    """
    H, W = x.shape
    new_H = H // pool_size
    new_W = W // pool_size
    pooled = np.zeros((new_H, new_W))

    # #############################################################
    # Your Turn: Divide the input into non-overlapping windows and compute
    # the maximum value from each window.
    # -------------------------------------------------------------
    for i in range(new_H):
      for j in range(new_W):
          patch = x[i*pool_size:(i+1)*pool_size, j*pool_size:(j+1)*pool_size]
          pooled[i, j] = np.max(patch)
    # #############################################################

    return pooled

dummy_feature_map = np.array([[1, 3, 2, 4],
                              [5, 6, 1, 2],
                              [7, 8, 9, 10],
                              [11,12,13,14]])
pool_size = 2
pool_output = max_pooling(dummy_feature_map, pool_size)
print("\nTask 3.2 - Max-Pooling Output:")
print(pool_output)


Task 3.2 - Max-Pooling Output:
[[ 6.  4.]
 [12. 14.]]


# Declaration of Independent Work  

I hereby declare that this assignment is entirely my own work and that I have neither given nor received unauthorized assistance in completing it. I have adhered to all the guidelines provided for this assignment and have cited all sources from which I derived data, ideas, or words, whether quoted directly or paraphrased.

Furthermore, I understand that providing false declaration is a violation of the University of Arizona's honor code and will result in appropriate disciplinary action consistent with the severity of the violation.

**Name:** Christian Ortmann  
**Date:** 03/07/2025